apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: Example service from GitHub
spec:
  type: service
  lifecycle: production
  owner: user:MonikaMorla




